services:
  grafana:
    image: grafana/grafana:10.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - tempo
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.51.2
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.10.0
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml:ro
    ports:
      - "3200:3200"
      - "4319:4317"
      - "4320:4318"

  loki:
    image: grafana/loki:2.9.8
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"

  alloy:
    image: grafana/alloy:v1.6.1
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
    command: ["run", "/etc/alloy/config.alloy"]
    ports:
      - "1517:4317"
      - "1518:4318"
    depends_on:
      - loki

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.145.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "14317:4317"
      - "14318:4318"
      - "19464:9464"
    depends_on:
      - tempo
      - loki

volumes:
  grafana_data:
